# Generated by Django 5.1.1 on 2024-10-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('responsibility', models.TextField()),
                ('minimum_qualifications', models.TextField()),
                ('preferred_qualifications', models.TextField()),
            ],
        ),
    ]
