# Generated by Django 5.1.1 on 2024-10-16 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_session_provider_alter_session_requester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_sessions', to='skills.skill'),
        ),
        migrations.AlterField(
            model_name='session',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_sessions', to='skills.skill'),
        ),
    ]
